[tool.black]
line-length = 88
target-version = ["py310"]
include = '\.pyi?$'
extend-exclude = '(/wicked_zerg_challenger/monitoring/|/wicked_zerg_challenger/tools/)'

[tool.isort]
profile = "black"
line_length = 88
known_first_party = [
  "src",
  "tests",
  "wicked_zerg_challenger",
  "scripts",
  "tools",
]
